### ISSUE TITLE
Looping on a login screen after installation

### ISSUE THREAD

**Issue by tzerber** [daxcurson/samba4_manager#1]
Hello there,

I'm trying your piece of software, but after a fresh install on Ubuntu 20.04 with all the requirements, the app keep reloading the login form. Using the administrator account in the Ldap to login and the correct password. I get this in the error log :
`[Tue Jan 11 11:50:43.219214 2022] [wsgi:error] [pid 19366:tid 139803046172416] [remote 192.168.0.144:18128] 2022-01-11 11:50:43,219 DEBUG [samba4_manager:372][Dummy-2] debug_authorization of url http://192.168.0.130/samba4_manager/ (view name '' against context <HTTPForbidden at 0x7f2653744520 403 Forbidden>): Allowed (NO_PERMISSION_REQUIRED)
[Tue Jan 11 11:50:43.219572 2022] [wsgi:error] [pid 19366:tid 139803046172416] [remote 192.168.0.144:18128] groupfinder: me llamaron con el userid Administrator@TESTLANDOMAIN y el request GET /samba4_manager/ HTTP/1.1\r
`

Both the standalone and Apache2 versions behave the same. The Samba AD does work, i have it connected to another PC.

Using :  Apache/2.4.41 
Samba : Version 4.13.14-Ubuntu
Python 3.8.10

I can provide additional logs if needed.

**Comment by daxcurson** [comment]
Hello, I'm so glad that you're trying my code ;-). To be honest, I haven't reviewed the code in a while, and in the meantime, the Pyramid framework that I had used originally was upgraded from 1.0 to 2.0 and I tried to adapt... with disastrous results. However, if you're trying to use my code, I'll give it another go, I'm glad it's receiving interest ;-)

**Comment by tzerber** [comment]
As you said, there's no Linux alternative. If you make it work a lot of people would like it i believe. I've spent some time researching and i found no alternative of the windows AD console for samba AD on linux.
EDIT:
I had issues installing it, due secureconfig not having version 0.2.0a0. After some googling i used this : 
[Comment by katrix001](https://github.com/nthmost/python-secureconfig/issues/3#issuecomment-647643835) and installed secureconfig version 0.1.1.0 to make pip happy.

Edit2: Looking at the secureconfig repository, there is a 0.2.0a0 ver, it's just not in pip. I will retry the whole installation with the github variant of secureconfig and try again.

Edit3 : Did the following : 
1) On a clean updated (as of writing) Ubuntu 20.04 with a working Samba4 AD installed : libffi-dev libssl-dev python3-pip apache2 apache2-dev 
2) installed configparser cffi mod_wsgi via pip ( pip install configparser cffi mod_wsgi)
3) Cloned and installed python-secureconfig repo and installed it manually ( git clone repo & cd repo & pip install .) 
Tried standalone mode - loops the login form.
4) Installed the apache module and loaded it.
Apache variant of the samba4 manager still loops the login form. It gives error upon entering the wrong user data, so i assume it's somewhat communicating with samba.

NOTE: edited pyramid.wsgi as follows 

```diff --git a/pyramid.wsgi b/pyramid.wsgi
index 5db8c0b..b8f8a88 100644
--- a/pyramid.wsgi
+++ b/pyramid.wsgi
@@ -1,4 +1,4 @@
 from pyramid.paster import get_app, setup_logging
-ini_path = '/mnt/c/dev-tools-and-data/web/proyectos/python/samba4_manager/development.ini'
+ini_path = '/var/www/html/samba4_manager/development.ini'
 setup_logging(ini_path)
 application = get_app(ini_path, 'main')
```

And the apache2 conf to 
```apacheconf
# Use only 1 Python sub-interpreter.  Multiple sub-interpreters
# play badly with C extensions.  See
# http://stackoverflow.com/a/10558360/209039
WSGIApplicationGroup %{GLOBAL}
WSGIPassAuthorization On
WSGIDaemonProcess pyramid user=www-data group=www-data threads=4 \
   python-path=/usr/bin/python3
WSGIScriptAlias /samba4_manager /var/www/html/samba4_manager/pyramid.wsgi

<Directory /var/www/html/samba4_manager>
  WSGIProcessGroup pyramid
  Require all granted
</Directory>
```

**Comment by daxcurson** [comment]
I was able to reproduce your problem, I'll continue to investigate. There is a problem with the Pyramid framework, it doesn't get to authenticate to Samba.
